// docs/.vuepress/components/CenteredImage.vue
<template>
  <div class="container">
    <img :src="src" :alt="alt" :width="width" :height="height">
    <div class="caption" v-if="!!caption">{{ caption }}</div>
  </div>
</template>

<script>
import { defineComponent } from 'vue'

export default defineComponent({
  props: {
    src: {
      required: true,
      type: String
    },
    alt: {
      required: true,
      type: String
    },
    caption: {
      type: String
    },
    width: {
      type: String
    },
    height: {
      type: String
    }
  }
})
</script>

<style scoped>
.caption {
  font-style: italic;
  color: var(--c-text);
}

.container {
  text-align: center;
}
</style>

// src/components/CenteredImage/index.tsx
import mediumZoom from 'medium-zoom';
import React, { useEffect } from 'react';
import styles from './styles.module.scss';

interface Props {
    src: string,
    alt: string,
    borderRadius?: string,
    caption?: string,
    width?: string,
    height?: string
}

const CenteredImage = (props: Props) => {
    useEffect(() => {
        mediumZoom(`.${styles.container} > img`, {
            background: "#000000dd"
        });
    }, []);

    return (
        <div className={styles.container}>
            <img src={props.src} alt={props.alt} width={props.width} height={props.height} style={{borderRadius: props.borderRadius}} />
            {props.caption && (
                <div className={styles.caption}>
                    {props.caption}
                </div>
            )}
        </div>
    )
};

CenteredImage.defaultProps = {
    borderRadius: "inherit"
}

export default CenteredImage;
