// docs/.vuepress/components/Back.vue
<template>
  <p>
    <RouterLink :to="link">🔙 Back to <b>{{ name }}</b></RouterLink>
  </p>
</template>

<script>
import { defineComponent } from 'vue'

export default defineComponent({
  props: {
    name: {
      required: true,
      type: String
    },
    link: {
      type: String,
      default: "../"
    }
  }
})
</script>

// src/components/Back/index.tsx
import React from "react";
import Link from "@docusaurus/Link";

interface Props {
  link: string;
  name: string;
}

const Back = ({ link, name }: Props) => {
  return (
    <p>
      <Link to={link}>
        🔙 Back to <b>{name}</b>
      </Link>
    </p>
  );
};

Back.defaultProps = {
  link: "../",
};

export default Back;
